server:
  port: 8085


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categorias/**
